'use client';
import {useEffect,useRef,useState} from 'react';
import mimiAudio from './mimi-audio.json';
import {Volume2, VolumeX, ChevronLeft, Sparkles, Mic, Square, Play, BookOpen, Star, Check, RotateCcw, X, Settings, Headphones, PawPrint, Home, ArrowUp} from 'lucide-react';

type Progress={name:string;step:number;word:number;quiz:number;completed:boolean;homework:string[]};
const INITIAL:Progress={name:'Jenny',step:0,word:0,quiz:0,completed:false,homework:[]};
const WORDS=[{word:'bake',meaning:'굽다',line:'오븐에서 쿠키를 굽고 있네!'},{word:'cake',meaning:'케이크',line:'맛있는 딸기 케이크야.'},{word:'lake',meaning:'호수',line:'넓고 잔잔한 호수가 보여.'},{word:'rake',meaning:'갈퀴',line:'낙엽을 모을 때 쓰는 갈퀴야.'},{word:'cape',meaning:'망토',line:'바람에 펄럭이는 망토야.'},{word:'tape',meaning:'테이프',line:'종이를 붙일 때 쓰는 테이프야.'},{word:'cave',meaning:'동굴',line:'바위 안에 동굴이 있네!'},{word:'wave',meaning:'파도',line:'바다에서 파도가 출렁출렁!'}];
const STAGES=['미미와 인사','짧은 a 소리','Magic e 발견','발음 따라 하기','그림 단어 연습','듣고 골라요','Magic e 붙이기','오늘의 숙제'];
const QUESTIONS=[{answer:'lake',choices:['cake','lake','rake']},{answer:'cape',choices:['tape','cave','cape']},{answer:'wave',choices:['wave','bake','lake']}];
function Word({text}:{text:string}){return <span lang="en">{text.split('').map((c,i)=><span key={i} className={c==='a'||(c==='e'&&i===text.length-1)?'magic-letter':''}>{c}</span>)}</span>}
function Picture({word}:{word:string}){return <img className="word-picture" src={'/images/'+word+'.webp'} alt={WORDS.find(w=>w.word===word)?.meaning||word}/>}
export default function Page(){
 const [p,setP]=useState<Progress>(INITIAL),[ready,setReady]=useState(false),[saveStatus,setSaveStatus]=useState(''),[tab,setTab]=useState('lesson'),[muted,setMuted]=useState(false),[speaking,setSpeaking]=useState(false),[notice,setNotice]=useState(''),[magic,setMagic]=useState(false),[answer,setAnswer]=useState(''),[correct,setCorrect]=useState(false),[recording,setRecording]=useState(false),[audioUrl,setAudioUrl]=useState(''),[settings,setSettings]=useState(false),[nameDraft,setNameDraft]=useState('Jenny'),[homeWord,setHomeWord]=useState('cake');
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),recTimer=useRef<ReturnType<typeof setTimeout>|null>(null),urlRef=useRef(''),playing=useRef<HTMLAudioElement|null>(null),saveSerial=useRef(Promise.resolve()),saveGeneration=useRef(0),mounted=useRef(true),audioGeneration=useRef(0);
 useEffect(()=>{mounted.current=true;fetch('/api/progress').then(async r=>{if(!r.ok)throw Error();return r.json() as Promise<{progress:Progress|null}>}).then(d=>{if(d.progress){setP(d.progress);setNameDraft(d.progress.name)}setSaveStatus('진도 불러왔어요');setReady(true)}).catch(()=>setSaveStatus('진도 연결이 안 됐어요 · 다시 연결'));return()=>{mounted.current=false;window.speechSynthesis?.cancel();stream.current?.getTracks().forEach(t=>t.stop());if(recTimer.current)clearTimeout(recTimer.current);if(urlRef.current)URL.revokeObjectURL(urlRef.current);playing.current?.pause()}},[]);
 useEffect(()=>{if(!ready)return;const generation=++saveGeneration.current;const timer=setTimeout(()=>{setSaveStatus('저장 중…');saveSerial.current=saveSerial.current.catch(()=>{}).then(async()=>{try{const r=await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});if(!r.ok)throw Error();if(mounted.current&&generation===saveGeneration.current)setSaveStatus('진도 저장됨')}catch{if(mounted.current&&generation===saveGeneration.current)setSaveStatus('저장이 안 됐어요 · 다시 저장')}})},600);return()=>clearTimeout(timer)},[p,ready]);
 useEffect(()=>{if(urlRef.current){URL.revokeObjectURL(urlRef.current);urlRef.current=''}setAudioUrl('');playing.current?.pause()},[p.step,p.word,homeWord,tab]);
 function stopAudio(){audioGeneration.current++;window.speechSynthesis?.cancel();playing.current?.pause();setSpeaking(false)}
 function speak(text:string,lang='en-US'){stopAudio();if(muted){setNotice('소리를 켜고 다시 눌러줘요.');return}const clipWords=text==='cap. cape!'?['cap','cape']:/^(bake|cake|lake|rake|cape|tape|cave|wave|cap)$/i.test(text.trim())?[text.trim().toLowerCase()]:[];const tutorClip=(mimiAudio as Record<string,string>)[text];if(clipWords.length||tutorClip){const generation=audioGeneration.current;let index=0;const playClip=()=>{if(generation!==audioGeneration.current)return;const clip=new Audio(tutorClip||'/audio/natural/'+clipWords[index]+'.wav');playing.current=clip;clip.preload='auto';clip.onplaying=()=>setSpeaking(true);clip.onended=()=>{if(generation!==audioGeneration.current)return;if(!tutorClip&&++index<clipWords.length)playClip();else setSpeaking(false)};clip.onerror=()=>{if(generation===audioGeneration.current){setSpeaking(false);setNotice('단어 음성을 불러오지 못했어요. 다시 듣기를 눌러주세요.')}};clip.play().catch(()=>{if(generation===audioGeneration.current){setSpeaking(false);setNotice('다시 듣기를 눌러 단어 음성을 재생해 주세요.')}})};playClip();return;}if(!('speechSynthesis' in window)){setNotice('이 브라우저에서는 안내 음성을 사용할 수 없어요. 화면의 안내를 읽어주세요.');return}const u=new SpeechSynthesisUtterance(text);u.lang=lang;const isExample=/^(bake|cake|lake|rake|cape|tape|cave|wave|cap|A)$/i.test(text.trim())||text==='cap. cape!';u.rate=isExample?.86*.8:.86;u.pitch=1.10;const voices=window.speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang===lang&&/sandy|flo/i.test(v.name))||voices.find(v=>v.lang===lang&&/samantha|aria|jenny|zira|victoria|female/i.test(v.name))||voices.find(v=>v.lang===lang&&/google/i.test(v.name))||voices.find(v=>v.lang===lang)||voices.find(v=>v.lang.startsWith('en'))||null;u.onstart=()=>setSpeaking(true);u.onend=()=>setSpeaking(false);u.onerror=e=>{setSpeaking(false);if(e.error!=='interrupted'&&e.error!=='canceled')setNotice('소리를 재생하지 못했어요. 다시 듣기를 눌러주세요.')};window.speechSynthesis.speak(u)}
 function move(step:number){stopAudio();if(recording)stopRecord();setMagic(false);setCorrect(false);setAnswer('');setNotice('');setP(v=>({...v,step}));window.scrollTo({top:0,behavior:'smooth'})}
 const name=p.name;
 const narration=p.step===0?`${name}, 안녕! 나는 미미야. 오늘은 알파벳 a에게 생기는 신기한 일을 알아볼 거야!`:p.step===1?`${name}, 이건 cap, 모자야. cap에서 a는 짧은 소리가 나. 단어를 잘 듣고 따라 해볼까?`:p.step===2?`${name}, 뒤에 magic e가 왔네! a와 e 사이에 자음 하나가 있을 때, 끝의 e는 조용히 있으면서 a가 자기 이름을 말하게 도와줘. a의 이름은 에이! cap이 cape가 됐어!`:p.step===3?`${name}, 입을 살짝 벌려 에에서 시작해서 이로 부드럽게 이어봐. 에이! 끝의 e는 따로 읽지 않아.`:p.step===4?`${name}, ${WORDS[p.word].line} 단어를 듣고 따라 해보자!`:p.step===5?`${name}, 단어를 듣고 맞는 그림을 골라줘!`:p.step===6?`${name}, magic e를 단어 끝에 붙여줘!`: `${name}, 잘했어! 오늘은 magic e를 만났어. 오늘 숙제는 Speed Phonics 2권 Unit 1, 4페이지부터 9페이지까지 엄마와 함께 풀어보기야!`;
 const englishWordLines=['We are baking cookies in the oven!','Look at this yummy strawberry cake!','This lake is calm and blue.','A rake helps us gather leaves.','Look at this lovely purple cape!','We can use tape to stick paper together.','Here is a cave in the rocks!','A wave is curling in the sea!'];
 const englishNarration=p.step===0?`Hi, ${name}! I'm Mimi. Let's discover a little magic with the letter a!`:p.step===1?`Look, ${name}! This is a cap. Listen to the short a sound in cap. Now say cap with me!`:p.step===2?`Look, ${name}! Magic e is here! With one consonant between a and e, the silent e helps a say its name. Cap becomes cape!`:p.step===3?`${name}, let's say long a! Start with your mouth a little open, then gently close it a little. Listen to A, then say cape. The final e is silent!`:p.step===4?`${name}, ${englishWordLines[p.word]} Listen to ${WORDS[p.word].word}, then say it with me!`:p.step===5?`${name}, listen to the word. Then tap the matching picture!`:p.step===6?`${name}, tap magic e and put it at the end of cap. Let's make cape!`:`Great job, ${name}! You discovered magic e! For homework, work on Unit 1 in Speed Phonics Book 2, pages 4 to 9, with your mom!`;
 const mimiButton=<button className={'mimi-says-button '+(speaking?'is-speaking':'')} onClick={()=>speak(englishNarration)} aria-label="Mimi says · 영어 안내 듣기"><Volume2 size={19}/><span>Mimi says</span>{speaking&&<span className="voice-bars" aria-hidden="true"><i/><i/><i/></span>}</button>;
 const magicHint=<div className="magic-hint"><ArrowUp className="hint-arrow" size={32} strokeWidth={3}/><span className="hint-sparkle sparkle-one" aria-hidden="true">✦</span><span className="hint-sparkle sparkle-two" aria-hidden="true">✧</span><strong lang="en">Tap the purple e!</strong><span>보라색 <b>e</b>를 눌러봐요!</span></div>;

 async function startRecord(){stopAudio();if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setNotice('이 브라우저에서는 녹음이 지원되지 않아요. 음성을 듣고 따라 말해보세요.');return}try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const chunks:BlobPart[]=[];const rec=new MediaRecorder(stream.current);recorder.current=rec;rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{stream.current?.getTracks().forEach(t=>t.stop());if(chunks.length){if(urlRef.current)URL.revokeObjectURL(urlRef.current);urlRef.current=URL.createObjectURL(new Blob(chunks,{type:rec.mimeType||'audio/webm'}));setAudioUrl(urlRef.current)}setRecording(false)};rec.onerror=()=>{setNotice('녹음이 중단됐어요. 다시 시도해 주세요.');stopRecord()};rec.start();setRecording(true);setNotice('말해보세요! 녹음은 최대 15초예요.');recTimer.current=setTimeout(stopRecord,15000)}catch{setNotice('마이크 사용을 허용한 뒤 다시 눌러주세요.')}}
 function stopRecord(){if(recTimer.current)clearTimeout(recTimer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());setRecording(false);setNotice('내 목소리를 다시 들어볼까?')}
 function listenRecording(){stopAudio();const a=new Audio(audioUrl);playing.current=a;a.play().catch(()=>setNotice('녹음을 재생하지 못했어요. 다시 녹음해 주세요.'))}
 function switchTab(next:string){stopAudio();if(recording)stopRecord();setTab(next);setNotice('');window.scrollTo({top:0})}
 function next(){if(p.step===4&&p.word<7){if(recording)stopRecord();stopAudio();setP(v=>({...v,word:v.word+1}));setNotice('');return}if(p.step===5&&p.quiz<3){stopAudio();setP(v=>({...v,quiz:v.quiz+1}));setCorrect(false);setAnswer('');return}if(p.step===6&&!magic)return;move(Math.min(p.step+1,7));if(p.step===6)setP(v=>({...v,completed:true}));}
 function selectAnswer(w:string){if(correct)return;setAnswer(w);if(w===QUESTIONS[Math.min(p.quiz,2)].answer){setCorrect(true);speak(`Yes, ${name}! You found it! Great job!`)}else speak("Let's listen one more time. Try again!")}
 const recordControls=<div className="record-controls"><button className={'soft-button '+(recording?'recording':'')} onClick={recording?stopRecord:startRecord}>{recording?<Square size={18}/>:<Mic size={18}/>} {recording?'녹음 멈추기':'따라 말하기 녹음'}</button>{audioUrl&&<button className="soft-button" onClick={listenRecording}><Play size={18}/> 내 목소리 듣기</button>}</div>;
 const tutor=<div className={'tutor-bubble '+(speaking?'talking':'')}><img src="/images/mimi.png" alt="하얀 털과 보라색 눈의 고양이 튜터 미미"/><div>{mimiButton}<p className="mimi-english" lang="en">{englishNarration}</p><p className="mimi-korean" lang="ko">{narration}</p></div></div>;
 return <main className="app"><header className="topbar"><button className="brand" onClick={()=>switchTab('lesson')} aria-label="미미 수업으로"><span className="brand-icon"><PawPrint size={21}/></span><span>Mimi’s <b>Phonics</b></span></button><div className="header-buttons"><button className="icon-button" onClick={()=>{stopAudio();setMuted(!muted)}} aria-label={muted?'소리 켜기':'소리 끄기'}>{muted?<VolumeX size={20}/>:<Volume2 size={20}/>}</button><button className="profile-button" onClick={()=>{setNameDraft(name);setSettings(true)}} aria-label="학생 이름 설정">{name.slice(0,1).toUpperCase()}</button></div></header>
 <section className="workspace"><div className="student-line"><span>HELLO, <b>{name.toUpperCase()}</b> <span className="tiny-star">✦</span></span><span className="unit-tag">UNIT 01</span></div>
 {tab==='lesson'&&<><div className="lesson-heading"><div><p className="eyebrow">미미와 함께하는 오늘의 수업</p><h1>Magic <span>e</span>의 마법</h1></div><span className="lesson-badge"><Sparkles size={18}/> Long a</span></div><div className="progress-row"><div className="progress-track" role="progressbar" aria-label="수업 진행" aria-valuenow={p.completed?100:Math.round(p.step/8*100)} aria-valuemin={0} aria-valuemax={100}><span style={{width:(p.completed?100:p.step/8*100)+'%'}}/></div><span>{p.step+1} / 8</span></div><div className="stage-line"><span>{STAGES[p.step]}</span><button className="lesson-menu-button" onClick={()=>switchTab('progress')} aria-label="전체 수업 보기 · 8단계 목차"><BookOpen size={20}/><span>전체 수업 보기</span></button></div>
 {p.step===0?<section className="welcome-card"><div className="welcome-top"><span className="pill">오늘의 작은 발견</span><span className="decoration-star">✦</span></div><h2>{name}, 만나서 반가워!</h2><p>작은 <b>e</b>가 만드는 커다란 변화</p><div className="cat-stage"><span className="floating-letter letter-a">a</span><img className={'hero-cat '+(speaking?'cat-speaking':'')} src="/images/mimi.png" alt="앉아서 Jenny를 반기는 하얀 고양이 미미"/><span className="floating-letter letter-e">e<span>✦</span></span><div className="cat-shadow"/></div><div className="welcome-speech">{mimiButton}<p className="mimi-english" lang="en">{englishNarration}</p><p className="mimi-korean" lang="ko">{narration}</p></div><div className="welcome-meta"><span><Headphones size={16}/> 듣고 따라 말해요</span><span><Star size={16}/> 약 8–10분</span></div></section>:<>
 {p.step===1&&<section className="activity-card"><span className="pill">먼저, 짧은 a 소리</span><div className="cap-art" role="img" aria-label="모자">🧢</div><div className="big-word"><Word text="cap"/></div><p className="meaning">모자</p><button className="audio-button" onClick={()=>speak('cap','en-US')}><Volume2 size={20}/> cap 듣기</button><p className="learning-note">a는 짧은 <b>/æ/</b> 소리예요.<br/>입을 벌리고 단어를 따라 해봐요.</p></section>}
 {p.step===2&&<section className="activity-card"><span className="pill">조용한 e의 특별한 마법</span><div className={'magic-scene '+(magic?'transformed':'')}>{magic?<Picture word="cape"/>:<div className="cap-art" role="img" aria-label="모자">🧢</div>}</div><div className="letter-building"><span>c</span><span className="magic-letter">a</span><span>p</span><button className={'e-button '+(magic?'attached':'')} onClick={()=>{setMagic(!magic);speak(!magic?'cape':'cap','en-US')}} aria-label="magic e 붙이기 또는 떼기">e<Sparkles size={19}/></button></div>{!magic&&magicHint}<p className="meaning">{magic?'cape · 망토':'cap · 모자'}</p><p className="learning-note">{magic?<>a가 자기 이름 <b>/eɪ/</b>를 말해요!<br/>끝의 e는 소리 내지 않아요.</>:<>작은 e가 오면 무엇이 달라질까요?</>}</p><div className="rule"><b>a</b><span>+ 자음 하나 +</span><b>e</b><span>=</span><strong>/eɪ/</strong></div><button className="audio-button" onClick={()=>speak(magic?'cape':'cap','en-US')}><Volume2 size={20}/> {magic?'cape':'cap'} 듣기</button></section>}
 {p.step===3&&<section className="activity-card pronunciation"><span className="pill">a가 자기 이름을 말해요</span><div className="sound-display">/eɪ/<span>에 → 이</span></div><h2>부드럽게 이어 말해요</h2><ol className="mouth-steps"><li><span>1</span>입을 살짝 벌려 ‘에’로 시작해요.</li><li><span>2</span>턱을 조금 올리며 ‘이’로 이어요.</li><li><span>3</span>두 소리를 끊지 않고 /eɪ/!</li></ol><div className="audio-pair"><button className="audio-button" onClick={()=>speak('A','en-US')}><Volume2 size={19}/> /eɪ/ 듣기</button><button className="soft-button" onClick={()=>speak('cape','en-US')}><Volume2 size={19}/> cape 듣기</button></div><p className="learning-note">끝의 e는 조용히! <b>cape</b>를 따라 해요.</p>{recordControls}</section>}
 {p.step===4&&<section className="activity-card vocabulary"><div className="card-top"><span className="pill">듣고, 보고, 따라 해요</span><span className="word-count">{p.word+1} / 8</span></div><Picture word={WORDS[p.word].word}/><div className="big-word"><Word text={WORDS[p.word].word}/></div><p className="meaning">{WORDS[p.word].meaning}</p><button className="audio-button" onClick={()=>speak(WORDS[p.word].word,'en-US')}><Volume2 size={20}/> 단어 듣기</button>{recordControls}<div className="word-dots">{WORDS.map((w,i)=><button key={w.word} className={p.word===i?'active':''} aria-label={w.word+' 카드 보기'} onClick={()=>{stopAudio();if(recording)stopRecord();setP(v=>({...v,word:i}))}}/>)}</div>{p.word===3&&<p className="break-note">반이나 배웠어, {name}! 잠깐 기지개 켜볼까?</p>}</section>}
 {p.step===5&&<section className="activity-card quiz-card"><span className="pill">그림 찾기 · {Math.min(p.quiz+1,3)} / 3</span>{p.quiz<3?<><h2>어떤 그림일까요?</h2><p className="subtitle">소리를 듣고 그림을 골라요.</p><button className="audio-button" onClick={()=>speak(QUESTIONS[p.quiz].answer,'en-US')}><Volume2 size={21}/> 문제 듣기</button><div className="choices">{QUESTIONS[p.quiz].choices.map(w=><button key={w} className={'choice '+(answer===w?(correct?'correct':'try-again'):'')} aria-label={WORDS.find(v=>v.word===w)?.meaning+' 그림 선택'} onClick={()=>selectAnswer(w)}><Picture word={w}/>{correct&&w===answer?<span><Word text={w}/><Check size={18}/></span>:<span className="choice-dot"/>}</button>)}</div><p className={'feedback '+(correct?'success':'')} role="status">{correct?'맞았어! 잘 찾았어, '+name+'!':answer?'괜찮아! 다시 듣고 골라볼까?':'천천히 들어도 괜찮아요.'}</p></>:<><div className="reward-star"><Star size={70} fill="currentColor"/></div><h2>세 문제 모두 찾았어요!</h2><p>이제 마지막 마법을 해볼까요?</p></>}</section>}
 {p.step===6&&<section className="activity-card"><span className="pill">{name}의 작은 마법</span><h2>Magic e를 붙여봐요!</h2><div className="magic-scene">{magic?<Picture word="cape"/>:<div className="cap-art" role="img" aria-label="모자">🧢</div>}</div><div className="letter-building"><span>c</span><span className="magic-letter">a</span><span>p</span>{magic?<span className="magic-letter">e</span>:<span className="letter-slot">?</span>}</div>{!magic?<><button className="magic-attach" onClick={()=>{setMagic(true);speak('cap. cape!','en-US')}}><span>e</span><Sparkles size={20}/> 터치해서 붙이기</button>{magicHint}</>:<><p className="feedback success">마법 성공! cap이 cape로 변했어요.</p><button className="audio-button" onClick={()=>speak('cape','en-US')}><Volume2 size={20}/> cape 듣기</button><button className="text-button" onClick={()=>setMagic(false)}><RotateCcw size={16}/> 다시 해보기</button></>}<p className="learning-note">조용한 e가 오면, a는 <b>/eɪ/</b>!</p></section>}
 {p.step===7&&<section className="activity-card finish-card"><span className="pill">UNIT 01 · 수업 완료</span><div className="reward-star"><Star size={68} fill="currentColor"/><Sparkles className="reward-spark" size={25}/></div><h2>잘했어, {name}!</h2><p>첫 번째 Magic e 별을 받았어요.</p><div className="sticker-label">MAGIC e EXPLORER</div><div className="mini-gallery">{WORDS.map(w=><button key={w.word} onClick={()=>speak(w.word,'en-US')} aria-label={w.word+' 다시 듣기'}><Picture word={w.word}/><Word text={w.word}/></button>)}</div><div className="homework-preview"><BookOpen size={21}/><div><b>오늘의 작은 숙제</b><p>Speed Phonics 2권 · Unit 1<br/>4~9페이지를 엄마와 함께 풀어보기</p></div></div><button className="audio-button" onClick={()=>switchTab('homework')}>숙제 만나보기</button></section>}
 {tutor}</>}
 <div className="lesson-actions">{p.step>0&&<button className="back-button" onClick={()=>{if(p.step===4&&p.word>0){stopAudio();if(recording)stopRecord();setP(v=>({...v,word:v.word-1}))}else move(p.step-1)}}><ChevronLeft size={18}/> 이전</button>}{p.step<7&&<button className="primary-button" disabled={(p.step===5&&p.quiz<3&&!correct)||(p.step===6&&!magic)||recording} onClick={()=>{if(p.step===0){speak(`Are you ready, ${name}? Let's learn together!`);setP(v=>({...v,step:1}))}else next()}}>{p.step===0?<><Sparkles size={20}/> 미미와 수업 시작</>:p.step===4&&p.word<7?'다음 단어':p.step===5&&p.quiz<3?'다음 문제':p.step===6?'별 받기':'다음으로'}</button>}</div></>}
 {tab==='homework'&&<><div className="lesson-heading"><div><p className="eyebrow">엄마와 함께 복습해요</p><h1>오늘의 <span>숙제</span></h1></div><BookOpen className="heading-icon" size={30}/></div><div className="homework-intro"><img src="/images/mimi.png" alt="미미"/><div><button className="mimi-says-button" onClick={()=>speak(`${name}, work on Unit 1 in Speed Phonics Book 2, pages 4 to 9, with your mom!`)} aria-label="Mimi says · 숙제 영어 안내 듣기"><Volume2 size={19}/><span>Mimi says</span></button><p className="mimi-english" lang="en">{name}, work on Unit 1 in Speed Phonics Book 2, pages 4 to 9, with your mom!</p><p className="mimi-korean" lang="ko">Speed Phonics 2권 Unit 1, 4~9페이지를 엄마와 함께 풀어봐요!</p></div></div><section className="workbook-task"><div className="workbook-task-header"><span className="workbook-icon"><BookOpen size={30}/></span><span className="pill">UNIT 01 · 교재 숙제</span></div><h2 lang="en">Speed Phonics <span>2</span></h2><p className="workbook-unit">2권 · Unit 1</p><div className="workbook-pages"><span>풀어볼 페이지</span><strong>4 — 9</strong></div><p className="workbook-instruction">엄마와 함께 풀어보기</p><button className={'homework-complete '+(p.homework.includes('book-unit1')?'checked':'')} aria-pressed={p.homework.includes('book-unit1')} onClick={()=>setP(v=>({...v,homework:v.homework.includes('book-unit1')?v.homework.filter(w=>w!=='book-unit1'):[...v.homework,'book-unit1']}))}><span className="task-check"><Check size={21}/></span>{p.homework.includes('book-unit1')?'엄마와 함께 숙제를 마쳤어요!':'다 풀었으면 완료 표시하기'}</button></section><div className="homework-status">{p.homework.includes('book-unit1')?<><Star size={20}/> 숙제도 끝냈어요, {name}!</>:<>엄마와 함께 차근차근 풀어봐요.</>}</div></>}

 {tab==='progress'&&<><div className="lesson-heading"><div><p className="eyebrow">차근차근, 나만의 속도로</p><h1>{name}의 <span>배움</span></h1></div><Star className="heading-icon" size={30}/></div><div className="progress-summary"><div className="small-star"><Star size={32} fill={p.completed?'currentColor':'none'}/></div><div><h2>Magic e · Long a</h2><p>{p.completed?'첫 단원 수업 완료!':'오늘도 미미와 배워봐요.'}</p></div></div><div className="lesson-list">{STAGES.map((s,i)=><button key={s} onClick={()=>{switchTab('lesson');move(i)}}><span className={'step-number '+(i<p.step||p.completed?'done':'')}>{i<p.step||p.completed?<Check size={17}/>:i+1}</span><span>{s}</span><span className="step-state">{i<p.step||p.completed?'복습하기':i===p.step?'이어하기':'살펴보기'}</span></button>)}</div><div className="homework-preview"><BookOpen size={22}/><div><b>{p.homework.includes('book-unit1')?'교재 숙제 완료':'교재 숙제가 남았어요'}</b><p>Speed Phonics 2권 · Unit 1 · 4~9페이지</p></div><button className="text-button" onClick={()=>switchTab('homework')}>보러 가기</button></div></>}
 {notice&&<p className="notice" role="status">{notice}</p>}<button className="save-status" onClick={()=>{if(!ready){fetch('/api/progress').then(async r=>{if(!r.ok)throw Error();return r.json() as Promise<{progress:Progress|null}>}).then(d=>{if(d.progress){setP(d.progress);setNameDraft(d.progress.name)}setReady(true);setSaveStatus('진도 불러왔어요')}).catch(()=>setSaveStatus('진도 연결이 안 됐어요 · 다시 연결'))}else setP(v=>({...v}))}} disabled={!saveStatus.includes('안 됐어요')} aria-label="진도 저장 상태 및 재시도">{saveStatus||'진도 연결 중…'}</button></section>
 <nav className="bottom-nav" aria-label="주요 메뉴">{[{id:'lesson',title:'오늘의 수업',Icon:Home},{id:'homework',title:'숙제',Icon:BookOpen},{id:'progress',title:'나의 배움',Icon:Star}].map(({id,title,Icon})=><button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>switchTab(id)}><Icon size={22}/><span>{title}</span>{id==='homework'&&p.completed&&!p.homework.includes('book-unit1')&&<i/>}</button>)}</nav>
 {settings&&<div className="modal-backdrop" onClick={()=>setSettings(false)}><section className="settings-modal" role="dialog" aria-modal="true" aria-labelledby="settings-title" onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" onClick={()=>setSettings(false)} aria-label="닫기"><X size={20}/></button><Settings size={26}/><h2 id="settings-title">미미가 부를 이름</h2><p>이름을 바꾸면 미미의 인사도 바뀌어요.</p><label htmlFor="student-name">학생 이름</label><input id="student-name" autoFocus maxLength={30} value={nameDraft} onChange={e=>setNameDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')setSettings(false)}}/><button className="soft-button" disabled={!nameDraft.trim()} onClick={()=>speak(`Hello, ${nameDraft.trim()}!`,'en-US')}><Volume2 size={18}/> 이름 들어보기</button><button className="primary-button" disabled={!nameDraft.trim()} onClick={()=>{setP(v=>({...v,name:nameDraft.trim()}));setSettings(false)}}>이 이름으로 배우기</button></section></div>}
 </main>
}
