'use client';
import {useEffect,useRef,useState} from 'react';
import mimiAudio from './mimi-audio.json';
import mimiSegments from './mimi-segments.json';
import {Volume2, VolumeX, ChevronLeft, Sparkles, Mic, Square, Play, BookOpen, Star, Check, RotateCcw, X, Settings, Headphones, PawPrint, Home, ArrowUp} from 'lucide-react';

type Progress={resetVersion:number;nameConfirmed:boolean;name:string;step:number;word:number;quiz:number;completed:boolean;homework:string[]};
const INITIAL:Progress={resetVersion:1,nameConfirmed:false,name:'',step:0,word:0,quiz:0,completed:false,homework:[]};
const WORDS=[{word:'bake',meaning:'굽다',line:'오븐에서 쿠키를 굽고 있네!'},{word:'cake',meaning:'케이크',line:'맛있는 딸기 케이크야.'},{word:'lake',meaning:'호수',line:'넓고 잔잔한 호수가 보여.'},{word:'rake',meaning:'갈퀴',line:'낙엽을 모을 때 쓰는 갈퀴야.'},{word:'cape',meaning:'망토',line:'바람에 펄럭이는 망토야.'},{word:'tape',meaning:'테이프',line:'종이를 붙일 때 쓰는 테이프야.'},{word:'cave',meaning:'동굴',line:'바위 안에 동굴이 있네!'},{word:'wave',meaning:'파도',line:'바다에서 파도가 출렁출렁!'}];
const STAGES=['Greeting','짧은 a 소리','Magic e 발견','발음 따라 하기','그림 단어 연습','듣고 골라요','Magic e 붙이기','오늘의 숙제'];
const QUESTIONS=[{answer:'lake',choices:['cake','lake','rake']},{answer:'cape',choices:['tape','cave','cape']},{answer:'wave',choices:['wave','bake','lake']}];
function Word({text}:{text:string}){return <span lang="en">{text.split('').map((c,i)=><span key={i} className={c==='a'||(c==='e'&&i===text.length-1)?'magic-letter':''}>{c}</span>)}</span>}
function Picture({word}:{word:string}){const src='/images/scenes/'+word+'.png';return <div className={'animated-scene scene-'+word} role="img" aria-label={word==='cap'?'모자를 쓴 미미':(WORDS.find(w=>w.word===word)?.meaning||word)+' 장면 속 움직이는 미미'}><img className="word-picture" src={src} alt=""/>{word==='wave'&&<><div className="wave-only-mask" aria-hidden="true"><img className="wave-layer" src={src} alt=""/></div><span className="wave-foam foam-one"/><span className="wave-foam foam-two"/></>}{word==='cave'&&<><span className="cave-shade"/><span className="bat-eyes eyes-one"><i/><i/></span><span className="bat-eyes eyes-two"><i/><i/></span></>}{word==='bake'&&<><svg className="baking-tray" viewBox="0 0 120 54" aria-hidden="true"><path d="M2 17 87 4 119 28 28 51Z" fill="#c9bbc7" stroke="#8e8399" strokeWidth="3"/>{[[26,22],[53,18],[80,14],[47,36],[77,31],[101,27]].map(([x,y],i)=><g key={i}><ellipse cx={x} cy={y} rx="10" ry="6" fill="#e9b16b"/><circle cx={x-3} cy={y} r="2" fill="#775149"/><circle cx={x+4} cy={y-2} r="1.5" fill="#775149"/></g>)}</svg><span className="baking-paw"/><span className="oven-glow"/></>}{word==='cake'&&<><span className="cake-bite" aria-hidden="true">🍰</span><span className="cake-crumb crumb-one"/><span className="cake-crumb crumb-two"/><span className="happy-heart" aria-hidden="true">♥</span></>}{word==='lake'&&<><span className="lake-ripple ripple-one"/><span className="lake-ripple ripple-two"/></>}{word==='rake'&&<><span className="moving-leaf leaf-one" aria-hidden="true">🍂</span><span className="moving-leaf leaf-two" aria-hidden="true">🍁</span></>}{word==='cape'&&<img className="cape-layer" src={src} alt=""/>}{word==='tape'&&<span className="tape-strip"/>}</div>}
export default function Page(){
 const [p,setP]=useState<Progress>(INITIAL),[ready,setReady]=useState(false),[saveStatus,setSaveStatus]=useState(''),[tab,setTab]=useState('lesson'),[muted,setMuted]=useState(false),[speaking,setSpeaking]=useState(false),[notice,setNotice]=useState(''),[magic,setMagic]=useState(false),[answer,setAnswer]=useState(''),[correct,setCorrect]=useState(false),[recording,setRecording]=useState(false),[audioUrl,setAudioUrl]=useState(''),[settings,setSettings]=useState(false),[nameDraft,setNameDraft]=useState(''),[homeWord,setHomeWord]=useState('cake');
 const [greetingLine,setGreetingLine]=useState(0),[showKorean,setShowKorean]=useState(false),[spokenCaption,setSpokenCaption]=useState('');
 const [registering,setRegistering]=useState(false),[registrationError,setRegistrationError]=useState('');
 const generatedClips=useRef(new Map<string,Promise<string>>());
 const greetingPending=useRef(false),greetingAudio=useRef<HTMLAudioElement|null>(null);
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),recTimer=useRef<ReturnType<typeof setTimeout>|null>(null),urlRef=useRef(''),playing=useRef<HTMLAudioElement|null>(null),saveSerial=useRef(Promise.resolve()),saveGeneration=useRef(0),mounted=useRef(true),audioGeneration=useRef(0);
 useEffect(()=>{mounted.current=true;fetch('/api/progress').then(async r=>{if(!r.ok)throw Error();return r.json() as Promise<{progress:Progress|null}>}).then(d=>{if(d.progress){setP(d.progress);setNameDraft(d.progress.name)}setSaveStatus('진도 불러왔어요');setReady(true)}).catch(()=>setSaveStatus('진도 연결이 안 됐어요 · 다시 연결'));return()=>{mounted.current=false;window.speechSynthesis?.cancel();stream.current?.getTracks().forEach(t=>t.stop());if(recTimer.current)clearTimeout(recTimer.current);if(urlRef.current)URL.revokeObjectURL(urlRef.current);playing.current?.pause();for(const clip of generatedClips.current.values())clip.then(url=>URL.revokeObjectURL(url)).catch(()=>{})}},[]);
 useEffect(()=>{if(!ready||!p.nameConfirmed)return;const generation=++saveGeneration.current;const timer=setTimeout(()=>{setSaveStatus('저장 중…');saveSerial.current=saveSerial.current.catch(()=>{}).then(async()=>{try{const r=await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});if(!r.ok)throw Error();if(mounted.current&&generation===saveGeneration.current)setSaveStatus('진도 저장됨')}catch{if(mounted.current&&generation===saveGeneration.current)setSaveStatus('저장이 안 됐어요 · 다시 저장')}})},600);return()=>clearTimeout(timer)},[p,ready]);
 useEffect(()=>{if(urlRef.current){URL.revokeObjectURL(urlRef.current);urlRef.current=''}setAudioUrl('');playing.current?.pause()},[p.step,p.word,homeWord,tab]);
 async function sameVoice(input:{scene?:string;index?:number;text?:string;name:string}){
  const key=JSON.stringify(input);const existing=generatedClips.current.get(key);if(existing)return existing;
  const task=(async()=>{for(let retry=0;retry<30;retry++){const r=await fetch('/api/mimi-voice',{method:'POST',headers:{'Content-Type':'application/json'},body:key});if(r.status===409){await new Promise(resolve=>setTimeout(resolve,1500));continue}if(!r.ok)throw Error('Mimi voice unavailable');return URL.createObjectURL(await r.blob())}throw Error('Voice timeout')})();
  generatedClips.current.set(key,task);task.catch(()=>generatedClips.current.delete(key));return task;
 }
 function stopAudio(){greetingPending.current=false;audioGeneration.current++;window.speechSynthesis?.cancel();playing.current?.pause();setSpeaking(false)}
 function speak(text:string,lang='en-US'){stopAudio();setSpokenCaption(text==='ay'?'/eɪ/':text);if(muted){setNotice('소리를 켜고 다시 눌러줘요.');return}const clipWords=text==='cap. cape!'?['cap','cape']:/^(bake|cake|lake|rake|cape|tape|cave|wave|cap)$/i.test(text.trim())?[text.trim().toLowerCase()]:[];const tutorClip=(mimiAudio as Record<string,string>)[text];if(clipWords.length||tutorClip){const generation=audioGeneration.current;let index=0;const playClip=()=>{if(generation!==audioGeneration.current)return;const clip=new Audio(tutorClip||'/audio/natural/'+clipWords[index]+'.wav');playing.current=clip;clip.preload='auto';clip.onplaying=()=>setSpeaking(true);clip.onended=()=>{if(generation!==audioGeneration.current)return;if(!tutorClip&&++index<clipWords.length)playClip();else setSpeaking(false)};clip.onerror=()=>{if(generation===audioGeneration.current){setSpeaking(false);setNotice('단어 음성을 불러오지 못했어요.')}};clip.play().catch(()=>{if(generation===audioGeneration.current){setSpeaking(false);setNotice('')}})};playClip();return;}const generation=audioGeneration.current;const previewName=text.match(/^Hello, (.+)!$/)?.[1]||p.name;sameVoice({text,name:previewName}).then(url=>{if(generation!==audioGeneration.current||!mounted.current)return;const clip=new Audio(url);playing.current=clip;clip.onplaying=()=>setSpeaking(true);clip.onended=()=>setSpeaking(false);return clip.play()}).catch(()=>{if(generation===audioGeneration.current){setSpeaking(false);setNotice('미미 음성을 준비하지 못했어요. 잠시 후 다시 시도해 주세요.')}})}
 const sceneKey=tab==='homework'?'homework':p.step===4?'4-'+WORDS[p.word].word:String(p.step);
 const sentenceClips=p.step===0&&tab==='lesson'?[
  {text:`Hi, ${p.name}!`,audio:'/audio/fena/greeting-natural-1.mp3'},
  {text:"I'm Mimi!",audio:'/audio/fena/greeting-natural-2.mp3'},
  {text:"Let's discover a little magic with the letter a!",audio:'/audio/fena/greeting-natural-3.mp3'}
 ]:((mimiSegments as Record<string,{text:string;audio:string}[]>)[sceneKey]||[]);
 function playGreeting(){
  stopAudio();setNotice('');setSpokenCaption('');setGreetingLine(0);if(muted||!sentenceClips.length)return;
  const generation=audioGeneration.current;
  async function playLine(index:number){
   if(generation!==audioGeneration.current||!mounted.current)return;
   if(index>=sentenceClips.length){setSpeaking(false);return}
   const sentence=sentenceClips[index];
   let source=sentence.audio;
   if(p.name!=='Jenny'&&(sentence.text.includes('Jenny')||(tab==='lesson'&&p.step===0&&index===0))){
    try{source=await sameVoice({scene:tab==='lesson'&&p.step===0?'greeting':sceneKey,index,name:p.name})}catch{if(generation===audioGeneration.current)setNotice('미미 음성을 준비하지 못했어요. 잠시 후 다시 시도해 주세요.');return}
    if(generation!==audioGeneration.current||!mounted.current)return;
   }
   const clip=greetingAudio.current||(greetingAudio.current=new Audio());clip.src=source;clip.preload='auto';playing.current=clip;
   clip.onplaying=()=>{setGreetingLine(index);greetingPending.current=false;setSpeaking(true)};
   clip.onended=()=>{if(generation!==audioGeneration.current)return;const wait=p.step===0?120:180;setTimeout(()=>playLine(index+1),wait)};
   clip.onerror=()=>{if(generation===audioGeneration.current)setSpeaking(false)};
   clip.play().catch(()=>{if(generation===audioGeneration.current){setSpeaking(false);greetingPending.current=true}});
  }
  playLine(0);
 }
 useEffect(()=>{
  setShowKorean(false);setGreetingLine(0);
  if(!ready||!p.nameConfirmed||tab==='progress')return;
  playGreeting();
  const resume=()=>{if(greetingPending.current&&!muted)playGreeting()};
  document.addEventListener('pointerdown',resume);document.addEventListener('keydown',resume);
  return()=>{document.removeEventListener('pointerdown',resume);document.removeEventListener('keydown',resume);stopAudio()};
 },[ready,tab,p.step,p.word,p.name,p.nameConfirmed,muted]);
 function move(step:number){stopAudio();if(recording)stopRecord();setMagic(false);setCorrect(false);setAnswer('');setNotice('');setP(v=>({...v,step}));window.scrollTo({top:0,behavior:'smooth'})}
 const name=p.name;
 const narration=p.step===0?`${name}, 안녕! 나는 미미야. 오늘은 알파벳 a에게 생기는 신기한 일을 알아볼 거야!`:p.step===1?`${name}, 이건 cap, 모자야. cap에서 a는 짧은 소리가 나. 단어를 잘 듣고 따라 해볼까?`:p.step===2?`cap이 magic e를 만나 cape가 됐어! a는 ‘에이’ 소리, 끝의 e는 조용해.`:p.step===3?`‘에이’를 듣고 cape를 따라 말해봐. 끝의 e는 소리 내지 않아.`:p.step===4?`${name}, ${WORDS[p.word].word}를 듣고 따라 말해보자!`:p.step===5?`${name}, 단어를 듣고 맞는 그림을 골라줘!`:p.step===6?`${name}, magic e를 단어 끝에 붙여줘!`: `${name}, 잘했어! 오늘은 magic e를 만났어. 오늘 숙제는 Speed Phonics 2권 Unit 1, 4페이지부터 9페이지까지 엄마와 함께 풀어보기야!`;
 const magicHint=<div className="magic-hint"><ArrowUp className="hint-arrow" size={32} strokeWidth={3}/><span className="hint-sparkle sparkle-one" aria-hidden="true">✦</span><span className="hint-sparkle sparkle-two" aria-hidden="true">✧</span><strong lang="en">Tap the purple e!</strong><span>보라색 <b>e</b>를 눌러봐요!</span></div>;

 async function startRecord(){stopAudio();if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setNotice('이 브라우저에서는 녹음이 지원되지 않아요. 음성을 듣고 따라 말해보세요.');return}try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const chunks:BlobPart[]=[];const rec=new MediaRecorder(stream.current);recorder.current=rec;rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{stream.current?.getTracks().forEach(t=>t.stop());if(chunks.length){if(urlRef.current)URL.revokeObjectURL(urlRef.current);urlRef.current=URL.createObjectURL(new Blob(chunks,{type:rec.mimeType||'audio/webm'}));setAudioUrl(urlRef.current)}setRecording(false)};rec.onerror=()=>{setNotice('녹음이 중단됐어요. 다시 시도해 주세요.');stopRecord()};rec.start();setRecording(true);setNotice('말해보세요! 녹음은 최대 15초예요.');recTimer.current=setTimeout(stopRecord,15000)}catch{setNotice('마이크 사용을 허용한 뒤 다시 눌러주세요.')}}
 function stopRecord(){if(recTimer.current)clearTimeout(recTimer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());setRecording(false);setNotice('내 목소리를 다시 들어볼까?')}
 function listenRecording(){stopAudio();const a=new Audio(audioUrl);playing.current=a;a.play().catch(()=>setNotice('녹음을 재생하지 못했어요. 다시 녹음해 주세요.'))}
 function switchTab(next:string){stopAudio();if(recording)stopRecord();setTab(next);setNotice('');window.scrollTo({top:0})}
 function next(){if(p.step===4&&p.word<7){if(recording)stopRecord();stopAudio();setP(v=>({...v,word:v.word+1}));setNotice('');return}if(p.step===5&&p.quiz<3){stopAudio();setP(v=>({...v,quiz:v.quiz+1}));setCorrect(false);setAnswer('');return}if(p.step===6&&!magic)return;move(Math.min(p.step+1,7));if(p.step===6)setP(v=>({...v,completed:true}));}
 function selectAnswer(w:string){if(correct)return;setAnswer(w);if(w===QUESTIONS[Math.min(p.quiz,2)].answer){setCorrect(true);speak(`Yes, ${name}! You found it! Great job!`)}else speak("Let's listen one more time. Try again!")}
 const recordControls=<div className="record-controls"><button className={'soft-button say-it-button '+(recording?'recording':'')} onClick={recording?stopRecord:startRecord}>{recording?<Square size={18}/>:<Mic size={18}/>} {recording?'Stop':'Say it'}</button>{audioUrl&&<button className="soft-button" onClick={listenRecording}><Play size={18}/> My voice</button>}</div>;
 const sceneWord=tab==='lesson'?(p.step===1?'cap':p.step===2||p.step===6?(magic?'cape':'cap'):p.step===3?'cape':p.step===4?WORDS[p.word].word:null):null;
 const phonetics:Record<string,string>={cap:'/æ/',bake:'/beɪk/',cake:'/keɪk/',lake:'/leɪk/',rake:'/reɪk/',cape:'/keɪp/',tape:'/teɪp/',cave:'/keɪv/',wave:'/weɪv/'};
 const tutor=<section className="narrative-card large-mimi-card"><div className="greeting-caption" aria-live="polite"><h2 key={sceneKey+'-'+greetingLine+'-'+spokenCaption} lang="en">{spokenCaption||(sentenceClips[Math.min(greetingLine,sentenceClips.length-1)]?.text||'').replaceAll('Jenny',name)}</h2></div><div className="mimi-caption-actions"><button className={'scene-round-button narration-replay '+(speaking?'is-speaking':'')} onClick={playGreeting} aria-label="Listen again · 미미 안내 다시 듣기"><Volume2 size={23}/></button><button className="scene-round-button korean-toggle" aria-label="한국어 번역" aria-expanded={showKorean} aria-controls="lesson-korean" onClick={()=>setShowKorean(v=>!v)}>한국어</button></div><div className="mimi-center"><div className={'lesson-cat-scene '+(speaking?'cat-speaking':'')} key={sceneWord||'mimi'}>{sceneWord?<Picture word={sceneWord}/>:<img src="/images/mimi.png" alt="고양이 튜터 미미"/>}</div></div>{sceneWord&&<div className="scene-word-block"><div className="scene-word-row">{p.step===2||p.step===6?<div className="letter-building"><span>c</span><span className="magic-letter">a</span><span>p</span>{p.step===2?<button className={'e-button '+(magic?'attached':'')} onClick={()=>{setMagic(!magic);speak(!magic?'cape':'cap')}} aria-label="magic e 붙이기 또는 떼기">e<Sparkles size={16}/></button>:magic?<span className="magic-letter">e</span>:<span className="letter-slot">?</span>}</div>:<div className="big-word"><Word text={sceneWord}/></div>}<button className="word-speaker" onClick={()=>speak(sceneWord)} aria-label={'Listen: '+sceneWord}><Volume2 size={23}/></button></div><p className="scene-phonetic"><span lang="en">{phonetics[sceneWord]}</span><span className="scene-word-meaning" lang="ko">{sceneWord==='cap'?'모자':WORDS.find(w=>w.word===sceneWord)?.meaning}</span></p>{p.step===2&&!magic&&magicHint}{p.step===6&&!magic&&<><button className="magic-attach" onClick={()=>{setMagic(true);speak('cape')}}><span>e</span><Sparkles size={20}/> Tap to add e</button>{magicHint}</>}{p.step===6&&magic&&<button className="text-button" onClick={()=>setMagic(false)}><RotateCcw size={16}/> Try again</button>}{p.step===4&&<><span className="scene-word-count">{p.word+1} / 8</span>{recordControls}<div className="word-dots">{WORDS.map((w,i)=><button key={w.word} className={p.word===i?'active':''} aria-label={w.word+' 카드 보기'} onClick={()=>{stopAudio();if(recording)stopRecord();setP(v=>({...v,word:i}));window.scrollTo({top:0,behavior:'smooth'})}}/>)}</div></>}</div>}<div id="lesson-korean" className={"translation-fold "+(showKorean?"expanded":"")} aria-hidden={!showKorean}><div><div className="welcome-speech"><p className="mimi-korean" lang="ko">{tab==='homework'?'Speed Phonics 2권 Unit 1, 4~9페이지를 엄마와 함께 풀어봐요!':narration}</p></div></div></div></section>;
 async function registerName(e:React.FormEvent){e.preventDefault();const chosen=nameDraft.trim();if(!chosen||registering)return;setRegistering(true);setRegistrationError('');stopAudio();try{const registered={...p,name:chosen,nameConfirmed:true,step:0};const r=await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(registered)});if(!r.ok)throw Error();setP(registered);setSaveStatus('진도 저장됨')}catch{setRegistrationError('이름을 저장하지 못했어요. 다시 시도해 주세요.')}finally{setRegistering(false)}}
 if(!ready)return <main className="app onboarding"><img src="/images/mimi.png" alt="미미"/><h1>Welcome to Mimi’s Phonics</h1><p>{saveStatus.includes('안 됐어요')?'수업에 연결하지 못했어요.':'Loading your lesson…'}</p>{saveStatus.includes('안 됐어요')&&<button className="primary-button" onClick={()=>window.location.reload()}>Try again</button>}</main>;
 if(!p.nameConfirmed)return <main className="app onboarding"><span className="onboarding-tag">MIMI’S PHONICS</span><img src="/images/mimi.png" alt="이름을 기다리는 고양이 미미"/><h1>What’s your name?</h1><p>미미가 부를 이름을 알려주세요.</p><form onSubmit={registerName}><label htmlFor="first-name">Your name</label><input id="first-name" autoComplete="given-name" maxLength={30} placeholder="Enter your name" value={nameDraft} onChange={e=>setNameDraft(e.target.value)} required disabled={registering}/><p className="name-note">이름과 수업 진도는 현재 로그인한 GPT 계정에 저장돼요.</p>{registrationError&&<p className="registration-error" role="alert">{registrationError}</p>}<button className="primary-button" type="submit" disabled={!nameDraft.trim()||registering}>{registering?'Saving…':'Meet Mimi'} <PawPrint size={19}/></button></form></main>;
 return <main className={"app "+(tab==='lesson'?'lesson-view':'')}><header className="topbar"><button className="brand" onClick={()=>switchTab('lesson')} aria-label="미미 수업으로"><span className="brand-icon"><PawPrint size={21}/></span><span>Mimi’s <b>Phonics</b></span></button><div className="header-buttons"><button className="icon-button" onClick={()=>{stopAudio();setMuted(!muted)}} aria-label={muted?'소리 켜기':'소리 끄기'}>{muted?<VolumeX size={20}/>:<Volume2 size={20}/>}</button><button className="profile-button" onClick={()=>{setNameDraft(name);setSettings(true)}} aria-label="학생 이름 설정">{name.slice(0,1).toUpperCase()}</button></div></header>
 <section className="workspace"><div className="student-line"><span>HELLO, <b>{name.toUpperCase()}</b> <span className="tiny-star">✦</span></span><span className="unit-tag">UNIT 01</span></div>
 {tab==='lesson'&&<><div className="lesson-heading"><div><p className="eyebrow">미미와 함께하는 오늘의 수업</p><h1>Magic <span>e</span>의 마법</h1></div><span className="lesson-badge"><Sparkles size={18}/> Long a</span></div><div className="progress-row"><div className="progress-track" role="progressbar" aria-label="수업 진행" aria-valuenow={p.completed?100:Math.round(p.step/8*100)} aria-valuemin={0} aria-valuemax={100}><span style={{width:(p.completed?100:p.step/8*100)+'%'}}/></div><span>{p.step+1} / 8</span></div><div className="stage-line"><span>{STAGES[p.step]}</span><button className="lesson-menu-button" onClick={()=>switchTab('progress')} aria-label="전체 수업 보기 · 8단계 목차"><BookOpen size={20}/><span>Lesson menu</span></button></div>
 {p.step===0?<>{tutor}<div className="welcome-meta"><span><Headphones size={16}/> 듣고 따라 말해요</span><span><Star size={16}/> 약 8–10분</span></div></>:<>{tutor}


 {p.step===3&&<section className="activity-card pronunciation"><span className="pill">a가 자기 이름을 말해요</span><div className="sound-display">/eɪ/<span>에 → 이</span></div><h2>부드럽게 이어 말해요</h2><ol className="mouth-steps"><li><span>1</span>입을 살짝 벌려 ‘에’로 시작해요.</li><li><span>2</span>턱을 조금 올리며 ‘이’로 이어요.</li><li><span>3</span>두 소리를 끊지 않고 /eɪ/!</li></ol><div className="audio-pair"><button className="audio-button" onClick={()=>speak('ay','en-US')}><Volume2 size={19}/> Listen: /eɪ/</button></div><p className="learning-note">끝의 e는 조용히! <b>cape</b>를 따라 해요.</p>{recordControls}</section>}

 {p.step===5&&<section className="activity-card quiz-card"><span className="pill">그림 찾기 · {Math.min(p.quiz+1,3)} / 3</span>{p.quiz<3?<><h2>어떤 그림일까요?</h2><p className="subtitle">소리를 듣고 그림을 골라요.</p><button className="audio-button" onClick={()=>speak(QUESTIONS[p.quiz].answer,'en-US')}><Volume2 size={21}/> Listen</button><div className="choices">{QUESTIONS[p.quiz].choices.map(w=><button key={w} className={'choice '+(answer===w?(correct?'correct':'try-again'):'')} aria-label={WORDS.find(v=>v.word===w)?.meaning+' 그림 선택'} onClick={()=>selectAnswer(w)}><Picture word={w}/>{correct&&w===answer?<span><Word text={w}/><Check size={18}/></span>:<span className="choice-dot"/>}</button>)}</div><p className={'feedback '+(correct?'success':'')} role="status">{correct?'맞았어! 잘 찾았어, '+name+'!':answer?'괜찮아! 다시 듣고 골라볼까?':'천천히 들어도 괜찮아요.'}</p></>:<><div className="reward-star"><Star size={70} fill="currentColor"/></div><h2>세 문제 모두 찾았어요!</h2><p>이제 마지막 마법을 해볼까요?</p></>}</section>}

 {p.step===7&&<section className="activity-card finish-card"><span className="pill">UNIT 01 · 수업 완료</span><div className="reward-star"><Star size={68} fill="currentColor"/><Sparkles className="reward-spark" size={25}/></div><h2>잘했어, {name}!</h2><p>첫 번째 Magic e 별을 받았어요.</p><div className="sticker-label">MAGIC e EXPLORER</div><div className="mini-gallery">{WORDS.map(w=><button key={w.word} onClick={()=>speak(w.word,'en-US')} aria-label={w.word+' 다시 듣기'}><Picture word={w.word}/><Word text={w.word}/></button>)}</div><div className="homework-preview"><BookOpen size={21}/><div><b>오늘의 작은 숙제</b><p>Speed Phonics 2권 · Unit 1<br/>4~9페이지를 엄마와 함께 풀어보기</p></div></div><button className="audio-button" onClick={()=>switchTab('homework')}>Homework</button></section>}
 </>}
 <div className="lesson-actions">{p.step>0&&<button className="back-button" disabled={p.step===4&&p.word===0} onClick={()=>{if(p.step===4&&p.word>0){stopAudio();if(recording)stopRecord();setP(v=>({...v,word:v.word-1}))}else move(p.step-1)}}><ChevronLeft size={18}/> Previous</button>}{p.step<7&&<button className="primary-button" disabled={(p.step===5&&p.quiz<3&&!correct)||(p.step===6&&!magic)||recording} onClick={()=>{if(p.step===0){move(1)}else next()}}>{p.step===0?<><Sparkles size={20}/> Start lesson</>:p.step===4&&p.word<7?'Next word':p.step===5&&p.quiz<3?'Next question':p.step===6?'Get my star':'Next'}</button>}</div></>}
 {tab==='homework'&&<><div className="lesson-heading"><div><p className="eyebrow">엄마와 함께 복습해요</p><h1>오늘의 <span>숙제</span></h1></div><BookOpen className="heading-icon" size={30}/></div>{tutor}<section className="workbook-task"><div className="workbook-task-header"><span className="workbook-icon"><BookOpen size={30}/></span><span className="pill">UNIT 01 · 교재 숙제</span></div><h2 lang="en">Speed Phonics <span>2</span></h2><p className="workbook-unit">2권 · Unit 1</p><div className="workbook-pages"><span>풀어볼 페이지</span><strong>4 — 9</strong></div><p className="workbook-instruction">엄마와 함께 풀어보기</p><button className={'homework-complete '+(p.homework.includes('book-unit1')?'checked':'')} aria-pressed={p.homework.includes('book-unit1')} onClick={()=>setP(v=>({...v,homework:v.homework.includes('book-unit1')?v.homework.filter(w=>w!=='book-unit1'):[...v.homework,'book-unit1']}))}><span className="task-check"><Check size={21}/></span>{p.homework.includes('book-unit1')?'Homework done!':'Mark as done'}</button></section><div className="homework-status">{p.homework.includes('book-unit1')?<><Star size={20}/> 숙제도 끝냈어요, {name}!</>:<>엄마와 함께 차근차근 풀어봐요.</>}</div></>}

 {tab==='progress'&&<><div className="lesson-heading"><div><p className="eyebrow">차근차근, 나만의 속도로</p><h1>{name}의 <span>배움</span></h1></div><Star className="heading-icon" size={30}/></div><div className="progress-summary"><div className="small-star"><Star size={32} fill={p.completed?'currentColor':'none'}/></div><div><h2>Magic e · Long a</h2><p>{p.completed?'첫 단원 수업 완료!':'오늘도 미미와 배워봐요.'}</p></div></div><div className="lesson-list">{STAGES.map((s,i)=><button key={s} onClick={()=>{switchTab('lesson');move(i)}}><span className={'step-number '+(i<p.step||p.completed?'done':'')}>{i<p.step||p.completed?<Check size={17}/>:i+1}</span><span>{s}</span><span className="step-state">{i<p.step||p.completed?'Review':i===p.step?'Continue':'Explore'}</span></button>)}</div><div className="homework-preview"><BookOpen size={22}/><div><b>{p.homework.includes('book-unit1')?'교재 숙제 완료':'교재 숙제가 남았어요'}</b><p>Speed Phonics 2권 · Unit 1 · 4~9페이지</p></div><button className="text-button" onClick={()=>switchTab('homework')}>Open</button></div></>}
 {notice&&<p className="notice" role="status">{notice}</p>}<button className="save-status" onClick={()=>{if(!ready){fetch('/api/progress').then(async r=>{if(!r.ok)throw Error();return r.json() as Promise<{progress:Progress|null}>}).then(d=>{if(d.progress){setP(d.progress);setNameDraft(d.progress.name)}setReady(true);setSaveStatus('진도 불러왔어요')}).catch(()=>setSaveStatus('진도 연결이 안 됐어요 · 다시 연결'))}else setP(v=>({...v}))}} disabled={!saveStatus.includes('안 됐어요')} aria-label="진도 저장 상태 및 재시도">{saveStatus||'진도 연결 중…'}</button></section>
 <nav className="bottom-nav" aria-label="주요 메뉴">{[{id:'lesson',title:'Lesson',Icon:Home},{id:'homework',title:'Homework',Icon:BookOpen},{id:'progress',title:'My progress',Icon:Star}].map(({id,title,Icon})=><button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>switchTab(id)}><Icon size={22}/><span>{title}</span>{id==='homework'&&p.completed&&!p.homework.includes('book-unit1')&&<i/>}</button>)}</nav>
 {settings&&<div className="modal-backdrop" onClick={()=>setSettings(false)}><section className="settings-modal" role="dialog" aria-modal="true" aria-labelledby="settings-title" onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" onClick={()=>setSettings(false)} aria-label="닫기"><X size={20}/></button><Settings size={26}/><h2 id="settings-title">미미가 부를 이름</h2><p>이름을 바꾸면 미미의 인사도 바뀌어요.</p><label htmlFor="student-name">학생 이름</label><input id="student-name" autoFocus maxLength={30} value={nameDraft} onChange={e=>setNameDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')setSettings(false)}}/><button className="soft-button" disabled={!nameDraft.trim()} onClick={()=>speak(`Hello, ${nameDraft.trim()}!`,'en-US')}><Volume2 size={18}/> Hear my name</button><button className="primary-button" disabled={!nameDraft.trim()} onClick={()=>{setP(v=>({...v,name:nameDraft.trim()}));setSettings(false)}}>Save name</button></section></div>}
 </main>
}
